services:

    uneak.field.helper:
        class: Uneak\FieldBundle\Field\FieldsHelper
        arguments:
            - @doctrine.orm.entity_manager
            - @uneak.fieldtypesmanager
            - @uneak.constraints.helper
            - @uneak.fielddatasmanager
            - @uneak.fielddata.helper
            - @uneak.fieldtypes.helper
            - @form.factory