services:

    uneak.fieldsearchmanager:
        class: Uneak\FieldSearchBundle\Field\FieldSearchManager


    uneak.fieldsearch.config.type.string:
        class: Uneak\FieldSearchBundle\Field\SearchType\StringSearchType
        tags:
            -  { name: uneak.fieldsearchmanager.field, alias_search: "search_string", field_data: "string" }

    uneak.fieldsearch.config.type.integer:
        class: Uneak\FieldSearchBundle\Field\SearchType\IntegerSearchType
        tags:
            -  { name: uneak.fieldsearchmanager.field, alias_search: "search_integer", field_data: "integer" }

    uneak.fieldsearch.config.type.boolean:
        class: Uneak\FieldSearchBundle\Field\SearchType\BooleanSearchType
        tags:
            -  { name: uneak.fieldsearchmanager.field, alias_search: "search_boolean", field_data: "boolean" }