parameters:
    uneak.oauth.facebook.credential.class: Uneak\OAuthClientBundle\OAuth\Credentials
    uneak.oauth.facebook.server.class: Uneak\OAuthFacebookServiceBundle\Services\FacebookServer
    uneak.oauth.facebook.service.class: Uneak\OAuthFacebookServiceBundle\Services\FacebookService
    uneak.oauth.facebook.authentication.class: Uneak\OAuthClientBundle\OAuth\Authentication
    uneak.oauth.facebook.api.class: Uneak\OAuthFacebookServiceBundle\Services\FacebookAPI


    facebook.api.url: "https://graph.facebook.com"
    facebook.auth.endpoint: "https://www.facebook.com/v2.0/dialog/oauth"
    facebook.token.endpoint: "https://graph.facebook.com/v2.0/oauth/access_token"
    facebook.revoke.token.endpoint: "https://graph.facebook.com/v2.0/me/permissions"
    facebook.client.id: "758175044305032"
    facebook.client.secret: "efafa1d80ee2ad0fb3e752aec3468bc5"


services:

    uneak.oauth.facebook.authentication:
        class: %uneak.oauth.facebook.authentication.class%
        arguments:
            - @uneak.oauth.facebook.credential
            - @uneak.oauth.facebook.server

    uneak.oauth.facebook.api:
        class: %uneak.oauth.facebook.api.class%
        arguments:
            - @uneak.oauth.facebook.service
            - %facebook.api.url%

    uneak.oauth.facebook.credential:
        class: %uneak.oauth.facebook.credential.class%
        arguments:
            - { clientId: %facebook.client.id%, clientSecret: %facebook.client.secret% }

    uneak.oauth.facebook.server:
        class: %uneak.oauth.facebook.server.class%
        arguments:
            - { authEndpoint: %facebook.auth.endpoint%, tokenEndpoint: %facebook.token.endpoint%, revokeTokenEndpoint: %facebook.revoke.token.endpoint% }

    uneak.oauth.facebook.service:
        class: %uneak.oauth.facebook.service.class%
        arguments:
            - @uneak.oauth.facebook.credential
            - @uneak.oauth.facebook.server
            - @uneak.oauth.facebook.authentication
            - %facebook.api.url%
        tags:
            - { name: uneak.oauth.service, alias: facebook }
