parameters:

    uneak.prospectmanager.class: Uneak\ProspectBundle\Prospect\ProspectsManager


services:

    uneak.prospectmanager:
        class: %uneak.prospectmanager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @uneak.fieldtypesmanager
            - @uneak.fielddatasmanager
            - @uneak.field.helper
            - @uneak.fielddata.helper
