parameters:
    uneak.oauth.twitter.credential.class: Uneak\OAuthClientBundle\OAuth\Configuration\CredentialsConfiguration
    uneak.oauth.twitter.server.class: Uneak\OAuthTwitterServiceBundle\Services\TwitterServerConfiguration
    uneak.oauth.twitter.service.class: Uneak\OAuthTwitterServiceBundle\Services\TwitterService
    uneak.oauth.twitter.authentication.class: Uneak\OAuthTwitterServiceBundle\Services\TwitterAuthenticationConfiguration

    uneak.oauth.twitter.api.class: Uneak\OAuthTwitterServiceBundle\Services\TwitterAPI
    uneak.oauth.twitter.user.class: Uneak\OAuthTwitterServiceBundle\Services\TwitterUser


#            'authorization_url' => '',
#            'request_token_url' => '',
#            'access_token_url'  => '',
#            'infos_url'         => 'https://api.twitter.com/1.1/account/verify_credentials.json',



    twitter.api.url: "https://api.twitter.com/1.1"


    twitter.request.token: "https://api.twitter.com/oauth/request_token"
    twitter.access.token: "https://api.twitter.com/oauth/access_token"
    twitter.authorization: "https://api.twitter.com/oauth/authenticate"

    twitter.client.id: "wWw1hP1RbJgjC6LyS9QmY3aKv"
    twitter.client.secret: "7DXjAi9KGq7SbXvuFjWF4qVAJARUE7mNzodub2Q0VMWbmafDkz"


services:

    uneak.oauth.twitter.authentication:
        class: %uneak.oauth.twitter.authentication.class%
        arguments:
            - { authorize_url: %twitter.authorization% }


    uneak.oauth.twitter.credential:
        class: %uneak.oauth.twitter.credential.class%
        arguments:
            - { clientId: %twitter.client.id%, clientSecret: %twitter.client.secret% }

    uneak.oauth.twitter.server:
        class: %uneak.oauth.twitter.server.class%
        arguments:
            - { request_token_url: %twitter.request.token%, access_token_url: %twitter.access.token% }

    uneak.oauth.twitter.service:
        class: %uneak.oauth.twitter.service.class%
        arguments:
            - @uneak.oauth.twitter.credential
            - @uneak.oauth.twitter.server
            - @uneak.oauth.twitter.authentication
        tags:
            - { name: uneak.oauth.service, alias: twitter }

    uneak.oauth.twitter.api:
        class: %uneak.oauth.twitter.api.class%
        arguments:
            - %twitter.api.url%
        tags:
            - { name: uneak.oauth.api, alias: twitter }

    uneak.oauth.twitter.user:
        class: %uneak.oauth.twitter.user.class%
        arguments:
            - @uneak.oauth.twitter.service
        tags:
            - { name: uneak.oauth.user, alias: twitter }