<?php

	namespace CampaignBundle\Entity;

    use Uneak\PortoAdminBundle\Entity\APIRepository;

    /**
	 * CampaignRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class CampaignRepository extends APIRepository {

	}
