<?php

	namespace RequestBundle\Entity;

    use Uneak\PortoAdminBundle\Entity\APIRepository;

    /**
	 * RequestRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class RequestRepository extends APIRepository {

	}
