<?php

	namespace Uneak\OAuthClientBundle\Entity;

	use Doctrine\ORM\EntityRepository;
	use Doctrine\ORM\Query\Expr;

	/**
	 * OAuthUserRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class OAuthUserRepository extends EntityRepository {



	}
