parameters:
    uneak.admin.client.admin.class: ClientBundle\Admin\Client
    uneak.admin.client.api.handler.class: ClientBundle\Handler\ClientAPIHandler
    uneak.admin.client.crud.handler.class: Uneak\PortoAdminBundle\Handler\CRUDHandler

    uneak.admin.client.role.admin.class: ClientBundle\Admin\ClientRole
    uneak.admin.client.role.api.handler.class: ClientBundle\Handler\ClientRoleAPIHandler
    uneak.admin.client.role.crud.handler.class: Uneak\PortoAdminBundle\Handler\CRUDHandler

services:

    uneak.admin.client.admin:
        class: %uneak.admin.client.admin.class%
        arguments: [ clients ]
        calls:
            - [ setController, [ ClientBundle\Controller\ClientAdminController ] ]
            - [ setHandler, [ @uneak.admin.client.crud.handler ] ]
        tags:
            -  { name: uneak.routesmanager.route }

    uneak.admin.client.api.handler:
        class: %uneak.admin.client.api.handler.class%
        arguments:
            - @form.factory
            - @doctrine.orm.entity_manager
            - "ClientBundle\Entity\Client"

    uneak.admin.client.crud.handler:
        class: %uneak.admin.client.crud.handler.class%
        arguments:
            - @uneak.admin.client.api.handler




    uneak.admin.client.role.admin:
        class: %uneak.admin.client.role.admin.class%
        arguments: [ clientroles ]
        calls:
            - [ setController, [ ClientBundle\Controller\ClientRoleAdminController ] ]
            - [ setHandler, [ @uneak.admin.client.role.crud.handler ] ]
        tags:
            -  { name: uneak.routesmanager.route }

    uneak.admin.client.role.api.handler:
        class: %uneak.admin.client.role.api.handler.class%
        arguments:
            - @form.factory
            - @doctrine.orm.entity_manager
            - "ClientBundle\Entity\Client"

    uneak.admin.client.role.crud.handler:
        class: %uneak.admin.client.role.crud.handler.class%
        arguments:
            - @uneak.admin.client.role.api.handler