<?php

	namespace Uneak\ImportBundle\Entity;

    use Uneak\PortoAdminBundle\Entity\APIRepository;

    /**
	 * ImportRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class ImportRepository extends APIRepository {


	}
