services:

    uneak.fielddata.form.fielddata.selector:
        class: Uneak\FieldDataBundle\Form\FieldDataSelectorType
        tags:
            -  { name: form.type, alias: "fielddatas_selector" }

    uneak.fielddata.helper:
        class: Uneak\FieldDataBundle\FieldData\FieldDataHelper
        arguments:
            - @doctrine.orm.entity_manager
