imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web
    assetic.filter.compass.http_path:  /


uneak_assets_manager:


    porto_admin_uielements_tabs_css:
        type: externalcss
        config:
            href: "css/porto_admin/ui-elements/tabs.css"

    porto_admin_entity_scroll_css:
        type: externalcss
        config:
            href: "css/porto_admin/entity-scroll.css"

    porto_admin_entity_css:
        type: externalcss
        config:
            href: "css/porto_admin/entity.css"

    porto_admin_theme_css:
        type: externalcss
        config:
            href: "css/porto_admin/theme.css"

    porto_admin_theme_custom_css:
        type: externalcss
        config:
            href: "css/porto_admin/theme-custom.css"

    porto_admin_theme_admin_extension_css:
        type: externalcss
        config:
            href: "css/porto_admin/theme-admin-extension.css"

    porto_admin_invoice_print_css:
        type: externalcss
        config:
            href: "css/porto_admin/invoice-print.css"

    bootstrap_css:
        type: externalcss
        config:
            href: "css/bootstrap.css"

    font_awesome_css:
        type: externalcss
        config:
            href: "css/font-awesome.css"



uneak_templates_manager:

#    member_connect_login: HWIOAuthBundle:Connect:login.html.twig
#    member_connect_registration_success: HWIOAuthBundle:Connect:registration_success.html.twig
#    member_connect_registration: HWIOAuthBundle:Connect:registration.html.twig
#    member_connect_connect_success: HWIOAuthBundle:Connect:connect_success.html.twig
#    member_connect_connect_confirm: HWIOAuthBundle:Connect:connect_confirm.html.twig
#    member_security_login: MemberBundle:Security:login.html.twig
#    member_resetting_request: MemberBundle:Resetting:request.html.twig
#    member_resetting_password_already_requested: MemberBundle:Resetting:passwordAlreadyRequested.html.twig
#    member_resetting_check_email: MemberBundle:Resetting:checkEmail.html.twig
#    member_resetting_reset: MemberBundle:Resetting:reset.html.twig
#    member_registration_email_txt: MemberBundle:Registration:email.txt.twig
#    member_registration_register: MemberBundle:Registration:register.html.twig
#    member_registration_check_email: MemberBundle:Registration:checkEmail.html.twig
#    member_registration_confirmed: MemberBundle:Registration:confirmed.html.twig
#    member_profile_show: MemberBundle:Profile:show.html.twig
#    member_profile_edit: MemberBundle:Profile:edit.html.twig
#    member_changepassword_change_password: MemberBundle:ChangePassword:changePassword.html.twig
#
#    block_card_script: UneakMaterialDesignBundle:Block:card_script.html.twig
#    block_card_template: UneakMaterialDesignBundle:Block:card.html.twig





framework:
    #esi:             ~
    ide: "phpstorm://open?file=%%f&line=%%l"
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java

    node: %assetic_node%
    ruby: %assetic_ruby%
    sass: %assetic_sass%

    filters:
        sass:
            bin: %assetic_sass%
            apply_to: "\.scss$"

        compass:
            bin: %assetic_compass%

        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

    assets:

        porto_admin_datatable_button_bootstrap__css:
            inputs:
                - %kernel.root_dir%/../web/vendor/datatables-buttons/css/buttons.bootstrap.scss
            filters:
                - sass
            output: css/porto_admin/datatable/buttons/buttons.bootstrap.css

        porto_admin_datatable_button_datatables__css:
            inputs:
                - %kernel.root_dir%/../web/vendor/datatables-buttons/css/buttons.dataTables.scss
            filters:
                - sass
            output: css/porto_admin/datatable/buttons/buttons.dataTables.css

        porto_admin_datatable_button_foundation__css:
            inputs:
                - %kernel.root_dir%/../web/vendor/datatables-buttons/css/buttons.foundation.scss
            filters:
                - sass
            output: css/porto_admin/datatable/buttons/buttons.foundation.css

        porto_admin_datatable_button_jqueryui__css:
            inputs:
                - %kernel.root_dir%/../web/vendor/datatables-buttons/css/buttons.jqueryui.scss
            filters:
                - sass
            output: css/porto_admin/datatable/buttons/buttons.jqueryui.css


        porto_admin_datatable_colreorder_datatables__css:
            inputs:
                - %kernel.root_dir%/../web/vendor/datatables-colreorder/css/colReorder.dataTables.scss
            filters:
                - sass
            output: css/porto_admin/datatable/colreorder/colReorder.dataTables.css

        porto_admin_datatable_colreorder_bootstrap__css:
            inputs:
                - %kernel.root_dir%/../web/vendor/datatables-colreorder/css/colReorder.bootstrap.scss
            filters:
                - sass
            output: css/porto_admin/datatable/colreorder/colReorder.bootstrap.css


        porto_admin_datatable_fixedheader_datatables__css:
            inputs:
                - %kernel.root_dir%/../web/vendor/datatables-fixedheader/css/fixedHeader.dataTables.scss
            filters:
                - sass
            output: css/porto_admin/datatable/fixedheader/fixedHeader.dataTables.css

        porto_admin_datatable_fixedheader_bootstrap__css:
            inputs:
                - %kernel.root_dir%/../web/vendor/datatables-fixedheader/css/fixedHeader.bootstrap.scss
            filters:
                - sass
            output: css/porto_admin/datatable/fixedheader/fixedHeader.bootstrap.css





        porto_admin_uielements_tabs__css:
            inputs:
                - %kernel.root_dir%/Resources/sass/porto_admin/modules/ui-elements/tabs.scss
            filters:
                - sass
            output: css/porto_admin/ui-elements/tabs.css

        porto_admin_entity__css:
            inputs:
                - %kernel.root_dir%/Resources/sass/porto_admin/entity.scss
            filters:
                - sass
            output: css/porto_admin/entity.css

        porto_admin_entity_scroll__css:
            inputs:
                - %kernel.root_dir%/Resources/sass/porto_admin/entity-scroll.scss
            filters:
                - sass
            output: css/porto_admin/entity-scroll.css

        porto_admin_theme__css:
            inputs:
                - %kernel.root_dir%/Resources/sass/porto_admin/theme.scss
            filters:
                - sass
            output: css/porto_admin/theme.css

        porto_admin_theme_custom__css:
            inputs:
                - %kernel.root_dir%/Resources/sass/porto_admin/theme-custom.scss
            filters:
                - sass
            output: css/porto_admin/theme-custom.css

        porto_admin_theme_admin_extension__css:
            inputs:
                - %kernel.root_dir%/Resources/sass/porto_admin/theme-admin-extension.scss
            filters:
                - sass
            output: css/porto_admin/theme-admin-extension.css

        porto_admin_invoice_print__css:
            inputs:
                - %kernel.root_dir%/Resources/sass/porto_admin/invoice-print.scss
            filters:
                - sass
            output: css/porto_admin/invoice-print.css

        bootstrap__css:
            inputs:
                - %kernel.root_dir%/Resources/sass/bootstrap/bootstrap.scss
            filters:
                - sass
            output: css/bootstrap.css

        font_awesome__css:
            inputs:
                - %kernel.root_dir%/Resources/sass/font-awesome/font-awesome.scss
            filters:
                - sass
            output: css/font-awesome.css


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                auto_mapping: true
                mappings:

                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            tree: false
            timestampable: true
            sluggable: true
            uploadable: false




# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }



# Fos User
fos_user:
    db_driver: orm
    firewall_name: user
    user_class: UserBundle\Entity\User
    group:
        group_class: UserBundle\Entity\Group
    registration:
        confirmation:
            enabled:    false # change to true for required email confirmation
            from_email: # Use this node only if you don't want the global email address for the confirmation email
                address: %contact_email%
                sender_name: %contact_name%
    resetting:
        token_ttl: 86400
        email:
            from_email: # Use this node only if you don't want the global email address for the resetting email
                address: %contact_email%
                sender_name: %contact_name%
        form:
            type:               fos_user_resetting
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword, Default]



# Fos Oauth
fos_oauth_server:
    db_driver: orm
    client_class: OAuthServerBundle\Entity\Client
    access_token_class: OAuthServerBundle\Entity\AccessToken
    refresh_token_class: OAuthServerBundle\Entity\RefreshToken
    auth_code_class: OAuthServerBundle\Entity\AuthCode

    service:
        user_provider: uneak.user_provider
        options:
            supported_scopes: user
            access_token_lifetime: 3600
            refresh_token_lifetime: 1209600
            auth_code_lifetime: 30


# Fos Rest
fos_rest:
    disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY #ROLE_API
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json



nelmio_api_doc:
    name:                 'Dashboard API documentation'
    exclude_sections:     []
    default_sections_opened:  true
    request_listener:
        enabled:              true
        parameter:            _doc
    cache:
        enabled:              false
        file:                 '%kernel.cache_dir%/api-doc.cache'


    sandbox:
        authentication:             # default is `~` (`null`), if set, the sandbox automatically
                                    # send authenticated requests using the configured `delivery`

            name: access_token      # access token name or query parameter name or header name

            delivery: http          # `query`, `http`, and `header` are supported

            # Required if http delivery is selected.
            type:     basic         # `basic`, `bearer` are supported

            custom_endpoint: false   # default is `false`, if `true`, your user will be able to
                                    # specify its own endpoint

        enabled:  true              # default is `true`, you can set this parameter to `false`
                                    # to disable the sandbox

        endpoint: /app_dev.php   # default is `/app_dev.php`, use this parameter
                                                # to define which URL to call through the sandbox

        accept_type: application/json           # default is `~` (`null`), if set, the value is
                                                # automatically populated as the `Accept` header

        body_format:
            formats: [ form, json ]             # array of enabled body formats,
                                                # remove all elements to disable the selectbox
            default_format: form                # default is `form`, determines whether to send
                                                # `x-www-form-urlencoded` data or json-encoded
                                                # data (by setting this parameter to `json`) in
                                                # sandbox requests

        request_format:
            formats:                            # default is `json` and `xml`,
                json: application/json          # override to add custom formats or disable
                xml: application/xml            # the default formats

            method: format_param    # default is `format_param`, alternately `accept_header`,
                                    # decides how to request the response format

            default_format: json    # default is `json`,
                                    # default content format to request (see formats)

        entity_to_choice: false     # default is `true`, if `false`, entity collection
                                    # will not be mapped as choice


# Liip Imagine
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: uploads/cache

    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web


    driver: gd
    cache: default
    data_loader: default
    controller:
        filter_action:  liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction

    filter_sets:
        cache: ~



# Bower
sp_bower:
    install_on_warmup: true
    allow_root: true
    keep_bowerrc: true
    bin: %bower%
    assetic: false
    bundles:
        AppBundle:
            config_dir: %kernel.root_dir%/../app/config
            asset_dir: %kernel.root_dir%/../web/vendor
            json_file: bower.json
            cache: %kernel.root_dir%/cache





# Vich Uploader
vich_uploader:
    db_driver: orm

    mappings:

        entity_image:
            uri_prefix:         /uploads
            upload_destination: %kernel.root_dir%/../web/uploads
            namer: vich_uploader.namer_uniqid
            directory_namer: uneak.entity.directory_namer

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
