
app:
    resource: "@AppBundle/Controller/"
    type:     annotation



oauth:
    resource: "@UneakOAuthClientBundle/Controller/"
    type:     annotation
    prefix: /





# FOS User
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#    prefix: /admin
#
#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /admin/group

uneak_member:
    resource: "@MemberBundle/Resources/config/routing.yml"
    prefix: /

uneak_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: admin






# uneak_routesmanager
uneak_routesmanager:
    resource: .
    type: uneak_routesmanager

# Lii Imagine
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"