app:
    resource: "@AppBundle/Controller/"
    type:     annotation


# FOS User
#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /admin/group


fos_user_group:
    resource: "@UserBundle/Resources/config/routing_member.yml"
    prefix: /






# HWI Oauth User
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook