app:
    resource: "@AppBundle/Controller/"
    type:     annotation

oauth:
    resource: "@UneakOAuthClientBundle/Controller/"
    type:     annotation
    prefix: /


user_api:
    type: rest
    resource: "@UserBundle/Resources/config/routing_api.yml"
    prefix: /api

oauth_server_api:
    type: rest
    resource: "@OAuthServerBundle/Resources/config/routing_api.yml"
    prefix: /api


prospect_api:
    type: rest
    resource: "@ProspectBundle/Resources/config/routing_api.yml"
    prefix: /api








uneak_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: admin


# uneak_routesmanager
uneak_routesmanager:
    resource: .
    type: uneak_routesmanager


# Lii Imagine
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


# NelmioApiDocBundle
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# Fos OAuth
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_oauth_server_login:
    path:     /oauth/v2/auth/login
    defaults: { _controller: OAuthServerBundle:Security:login }

fos_oauth_server_check:
    path:     /oauth/v2/auth/login_check
    defaults: { _controller: OAuthServerBundle:Security:loginCheck }