app:
    resource: "@AppBundle/Controller/"
    type:     annotation


# FOS User
#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#    prefix: /admin
#
#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /admin/group


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile



user_admin_registration:
    pattern:  admin/register
    defaults: { _controller: UserBundle:UserAdmin:register }

user_user_registration:
    pattern:  /register
    defaults: { _controller: UserBundle:UserUser:register }




# HWI Oauth User
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook