app:
    resource: "@AppBundle/Controller/"
    type:     annotation






# FOS User
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /admin

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/group

uneak_member:
    resource: "@MemberBundle/Resources/config/routing_member.yml"
    prefix: /


# HWI Oauth User
hwi_oauth_connect:
    path: /connect
    defaults: { _controller: MemberBundle:Connect:connect }

hwi_oauth_connect_service:
    path: /connect/service/{service}
    defaults: { _controller: MemberBundle:Connect:connectService }

hwi_oauth_connect_registration:
    path: /connect/registration/{key}
    defaults: { _controller: MemberBundle:Connect:registration }

hwi_oauth_service_redirect:
    path: /connect/{service}
    defaults: { _controller: MemberBundle:Connect:redirectToService }

facebook_login:
    path: /connect/check-facebook

google_login:
    pattern: /connect/check-google


twitter_login:
    pattern: /connect/check-twitte



# uneak_routesmanager
uneak_routesmanager:
    resource: .
    type: uneak_routesmanager

# Lii Imagine
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"