# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
#        fos_userbundle:
#            id: fos_user.user_provider.username

        uneak_user:
            id: uneak.user_provider.username

        uneak_member:
            id: uneak.member_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user:
#            pattern: ^/admin

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                provider: uneak_user
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                login_path:  user_security_login
                check_path:  user_security_check
                default_target_path: user_profile_show
            logout:
                path: user_security_logout
                target: user_security_login

            oauth:
                resource_owners:
                    facebook: /admin/connect/check-facebook
                    google: /admin/connect/check-google
                    twitter: /admin/connect/check-twitter

                check_path: /admin/connect
                login_path: /admin/login
                failure_path: /admin/connect
                default_target_path: user_profile_show
                use_forward: false

                oauth_user_provider:
                    service: uneak.user_provider

            anonymous:    true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate


        member:
            anonymous: ~

            form_login:
                provider: uneak_member
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                login_path:  member_security_login
                check_path:  member_security_check
            logout:
                path: member_security_logout
                target: member_security_login

            oauth:
                resource_owners:
                    facebook: /connect/check-facebook
                    google: /connect/check-google
                    twitter: /connect/check-twitter

                check_path: /connect
                login_path: /login
                failure_path: /connect
                use_forward: false

                oauth_user_provider:
                    service: uneak.member_provider


    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }