parameters:

    uneak.admin.app.admin.class: Uneak\RoutesManagerBundle\Routes\NestedRoute

services:

    uneak.admin.app.admin:
        class: %uneak.admin.app.admin.class%
        arguments: [ admin ]
        calls:
            - [ setPath, [ '' ] ]
            - [ setAction, [ 'index' ] ]
            - [ setMetaData, [ '_icon', 'tachometer' ] ]
            - [ setMetaData, [ '_label', 'Accueil' ] ]
            - [ setMetaData, [ '_description', 'Accueil' ] ]
            - [ setController, [ AppBundle\Controller\AdminController ] ]
        tags:
            -  { name: uneak.routesmanager.route }
