parameters:
    uneak.templatesmanager.class: Uneak\TemplatesManagerBundle\Templates\TemplatesManager

services:

    uneak.templatesmanager:
        class: %uneak.templatesmanager.class%
        arguments:
            - %uneak_templates%
