<?php

	namespace UserBundle\Entity;

	use Doctrine\ORM\EntityRepository;
	use Doctrine\ORM\Query\Expr;
	use Doctrine\ORM\QueryBuilder;

	/**
	 * MemberRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class MemberRepository extends EntityRepository {

	}
