<?php

	namespace UserBundle\Entity;

	use Doctrine\ORM\EntityRepository;
	use Doctrine\ORM\Query\Expr;
	use Doctrine\ORM\QueryBuilder;

	/**
	 * UserRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class UserRepository extends EntityRepository {

		public function findPendingAccount() {
			$qb = $this->getPendingAccountQuery();
			$query = $qb->getQuery();
			return $query->getResult();
		}

		public function getPendingAccountQuery() {
			$qb = $this->_em->createQueryBuilder();
			$qb->select(array('user'))
				->from('UserBundle:User', 'user')
				->where($qb->expr()->andX(
					$qb->expr()->eq('user.stateProfile', ':state'),
					$qb->expr()->eq('user.emailConfirmed', true)
				))
				->setParameter('state', User::STATE_PROFILE_PENDING)
				->orderBy("user.createdAt", "ASC")
			;
			return $qb;
		}

	}
