<?php

	namespace Uneak\FieldGroupBundle\Entity;

    use Uneak\PortoAdminBundle\Entity\APIRepository;

    /**
	 * FieldGroupRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class FieldGroupRepository extends APIRepository {

	}
