<?php

	namespace ProspectGroupBundle\Entity;

    use Uneak\PortoAdminBundle\Entity\APIRepository;

    /**
	 * ProspectGroupRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class ProspectGroupRepository extends APIRepository {

	}
