<?php

	namespace ClientBundle\Entity;

    use Uneak\PortoAdminBundle\Entity\APIRepository;

    /**
	 * ClientUserRoleRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class ClientUserRoleRepository extends APIRepository {

	}
