parameters:
    uneak.oauth.google.credential.class: Uneak\OAuthClientBundle\OAuth\Configuration\CredentialsConfiguration
    uneak.oauth.google.server.class: Uneak\OAuthGoogleServiceBundle\Services\GoogleServerConfiguration
    uneak.oauth.google.service.class: Uneak\OAuthGoogleServiceBundle\Services\GoogleService
    uneak.oauth.google.authentication.class: Uneak\OAuthClientBundle\OAuth\Configuration\AuthenticationConfiguration

    uneak.oauth.google.api.class: Uneak\OAuthGoogleServiceBundle\Services\GoogleAPI
    uneak.oauth.google.user.class: Uneak\OAuthGoogleServiceBundle\Services\GoogleUser


    google.api.url: "https://www.googleapis.com/oauth2/v1"
    
    google.auth.endpoint: "https://accounts.google.com/o/oauth2/auth"
    google.token.endpoint: "https://accounts.google.com/o/oauth2/token"
    google.revoke.token.endpoint: "https://accounts.google.com/o/oauth2/revoke"
    google.client.id: "214715913175-lrvi6it9ohi11ce13g6e2gsar3114p3d.apps.googleusercontent.com"
    google.client.secret: "qWirg4dtgSQayvEML9dv07Ky"

    google.auth.code.scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"



services:

    uneak.oauth.google.authentication:
        class: %uneak.oauth.google.authentication.class%
        arguments:
            - { scope: %google.auth.code.scope% }

    uneak.oauth.google.credential:
        class: %uneak.oauth.google.credential.class%
        arguments:
            - { clientId: %google.client.id%, clientSecret: %google.client.secret% }

    uneak.oauth.google.server:
        class: %uneak.oauth.google.server.class%
        arguments:
            - { authEndpoint: %google.auth.endpoint%, tokenEndpoint: %google.token.endpoint%, revokeTokenEndpoint: %google.revoke.token.endpoint% }

    uneak.oauth.google.service:
        class: %uneak.oauth.google.service.class%
        arguments:
            - @uneak.oauth.google.credential
            - @uneak.oauth.google.server
            - @uneak.oauth.google.authentication
        tags:
            - { name: uneak.oauth.service, alias: google }

    uneak.oauth.google.api:
        class: %uneak.oauth.google.api.class%
        arguments:
            - %google.api.url%
        tags:
            - { name: uneak.oauth.api, alias: google }
         
    uneak.oauth.google.user:
        class: %uneak.oauth.google.user.class%
        tags:
            - { name: uneak.oauth.user, alias: google }