<?php

	namespace GroupFieldBundle\Entity;

    use Uneak\PortoAdminBundle\Entity\APIRepository;

    /**
	 * GroupFieldRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class GroupFieldRepository extends APIRepository {

	}
