parameters:
    uneak_templates:

        block_card_script: UneakMaterialDesignBlocksBundle:Block:card_script.html.twig
        block_card_template: UneakMaterialDesignBlocksBundle:Block:card.html.twig