
porto_admin_fonts_css:
    type: externalcss
    config:
        href: "http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light"

porto_admin_theme_css:
    type: externalcss
    config:
        href: "bundles/uneakportoadmin/css/theme.css"
        dependencies: [ "bootstrap_css", "porto_admin_fonts_css", "font_awesome_css" ]

porto_admin_skins_default_css:
    type: externalcss
    config:
        href: "bundles/uneakportoadmin/css/skins/default.css"
        dependencies: [ "porto_admin_theme_css" ]

porto_admin_theme_custom_css:
    type: externalcss
    config:
        href: "bundles/uneakportoadmin/css/theme-custom.css"
        dependencies: [ "porto_admin_skins_default_css" ]

font_awesome_css:
    type: externalcss
    config:
        href: "vendor/font-awesome/css/font-awesome.css"

bootstrap_css:
    type: externalcss
    config:
        href: "vendor/bootstrap/dist/css/bootstrap.css"

modernizr_js:
    type: externaljs
    config:
#        src: "vendor/modernizr/modernizr.js"
        src: "bundles/uneakportoadmin/js/modernizr.js"
        category: "AssetExternalJs_top"

jquery_js:
    type: externaljs
    config:
        src: "vendor/jquery/dist/jquery.js"

jquery_browser_mobile_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/jquery.browser.mobile.js"
        dependencies: [ "jquery_js" ]

bootstrap_js:
    type: externaljs
    config:
        src: "vendor/bootstrap/dist/js/bootstrap.js"
        dependencies: [ "jquery_js" ]

nanoscroller_js:
    type: externaljs
    config:
        src: "vendor/nanoscroller/bin/javascripts/jquery.nanoscroller.js"
#        src: "bundles/uneakportoadmin/js/nanoscroller.js"
        dependencies: [ "jquery_js" ]

jquery_placeholder_js:
    type: externaljs
    config:
        src: "vendor/jquery-placeholder/jquery.placeholder.js"
        dependencies: [ "jquery_js" ]




porto_admin_window_theme_js:
    type: internaljs
    config:
        content: "window.theme = {};"
        category: "AssetExternalJs_theme"

porto_admin_theme_navigation_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/navigation.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_scroll_to_top_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/scroll_to_top.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_skeleton_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/skeleton.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_base_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/base.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_theme_skeleton_js" ]

porto_admin_theme_mail_box_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/mail_box.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_lock_screen_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/lock_screen.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_panels_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/panels.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_bootstrap_toggle_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/bootstrap_toggle.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_form_to_object_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/form_to_object.js"
        category: "AssetExternalJs_theme"


porto_admin_theme_loading_overlay_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/loading_overlay.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]


porto_admin_theme_codemirror_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/codemirror.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_color_picker_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/color_picker.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_date_picker_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/date_picker.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_ios_switcher_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/ios_switcher.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_markdown_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/markdown.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_masked_input_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/masked_input.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_max_length_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/max_length.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_multi_select_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/multi_select.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_select2_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/select2.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_spinner_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/spinner.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_summer_note_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/summer_note.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_textarea_autosize_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/textarea_autosize.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_time_picker_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/time_picker.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_map_builder_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/map_builder.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]


porto_admin_theme_animate_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/animate.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_carousel_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/carousel.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_chart_circular_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/chart_circular.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_lightbox_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/lightbox.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_portlets_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/portlets.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_scrollable_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/scrollable.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_slider_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/slider.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_toggle_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/toggle.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_widget_todo_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/widget_todo.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_widget_toggle_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/widget_toggle.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_word_rotate_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/word_rotate.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]

porto_admin_theme_datatable_config_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/datatable_config.js"
        category: "AssetExternalJs_theme"

porto_admin_theme_notifications_config_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme/notifications_config.js"
        category: "AssetExternalJs_theme"
        dependencies: [ "porto_admin_window_theme_js" ]


#porto_admin_theme_js:
#    type: externaljs
#    config:
#        src: "bundles/uneakportoadmin/js/theme.js"
#        category: "AssetExternalJs_theme"

porto_admin_theme_custom_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme.custom.js"
        category: "AssetExternalJs_theme_custom"

porto_admin_theme_init_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme.init.js"
        category: "AssetExternalJs_theme_init"

porto_admin_theme_init_popover_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme.init/popover.js"
        category: "AssetExternalJs_theme_init"
        dependencies: [ "bootstrap_js" ]

porto_admin_theme_init_tooltip_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme.init/tooltip.js"
        category: "AssetExternalJs_theme_init"
        dependencies: [ "bootstrap_js" ]

porto_admin_theme_init_sidebar_widget_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme.init/sidebar_widget.js"
        category: "AssetExternalJs_theme_init"
        dependencies: [ "jquery_js" ]

porto_admin_theme_init_ios_switcher_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme.init/ios_switcher.js"
        category: "AssetExternalJs_theme_init"
        dependencies: [ "jquery_js" ]


porto_admin_theme_init_codemirror_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme.init/codemirror.js"
        category: "AssetExternalJs_theme_init"
        dependencies: [ "porto_admin_theme_codemirror_js" ]

porto_admin_theme_init_color_picker_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme.init/color_picker.js"
        category: "AssetExternalJs_theme_init"
        dependencies: [ "porto_admin_theme_color_picker_js", "jquery_js" ]

porto_admin_theme_init_date_picker_js:
    type: externaljs
    config:
        src: "bundles/uneakportoadmin/js/theme.init/date_picker.js"
        category: "AssetExternalJs_theme_init"
        dependencies: [ "porto_admin_theme_date_picker_js", "jquery_js" ]


#porto_admin_theme_admin_extension_css:
#    type: externalcss
#    config:
#        href: "bundles/uneakportoadmin/css/theme-admin-extension.css"
#
#porto_admin_invoice_print_css:
#    type: externalcss
#    config:
#        href: "bundles/uneakportoadmin/css/invoice-print.css"



