parameters:
    uneak.portoadmin.menu.template.class: Uneak\PortoAdminBundle\Templates\Menu\MenuTemplate
    uneak.portoadmin.mainmenu.template.class: Uneak\PortoAdminBundle\Templates\Menu\MainMenuTemplate
    uneak.portoadmin.usermenu.template.class: Uneak\PortoAdminBundle\Templates\Menu\UserMenuTemplate

    uneak.portoadmin.user.template.class: Uneak\PortoAdminBundle\Templates\User\UserTemplate
    uneak.portoadmin.breadcrumb.template.class: Uneak\PortoAdminBundle\Templates\Breadcrumb\BreadcrumbTemplate

    uneak.portoadmin.notifications.template.class: Uneak\PortoAdminBundle\Templates\Notification\NotificationsTemplate
    uneak.portoadmin.notification.template.class: Uneak\PortoAdminBundle\Templates\Notification\NotificationTemplate

    uneak.portoadmin.progress.bar.notification.template.class: Uneak\PortoAdminBundle\Templates\Notification\ProgressBarTemplate
    uneak.portoadmin.message.notification.template.class: Uneak\PortoAdminBundle\Templates\Notification\MessageTemplate
    uneak.portoadmin.icon.message.notification.template.class: Uneak\PortoAdminBundle\Templates\Notification\IconMessageTemplate

    uneak.portoadmin.search.template.class: Uneak\PortoAdminBundle\Templates\Search\SearchTemplate

    uneak.portoadmin.brand.template.class: Uneak\PortoAdminBundle\Templates\Brand\BrandTemplate

services:
    uneak.portoadmin.menu.template:
        class: %uneak.portoadmin.menu.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_menu }

    uneak.portoadmin.mainmenu.template:
        class: %uneak.portoadmin.mainmenu.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_main_menu }

    uneak.portoadmin.usermenu.template:
        class: %uneak.portoadmin.usermenu.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_user_menu }

    uneak.portoadmin.user.template:
        class: %uneak.portoadmin.user.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_user }

    uneak.portoadmin.breadcrumb.template:
        class: %uneak.portoadmin.breadcrumb.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_breadcrumb }

    uneak.portoadmin.notifications.template:
        class: %uneak.portoadmin.notifications.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_notifications }

    uneak.portoadmin.notification.template:
        class: %uneak.portoadmin.notification.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_notification }

    uneak.portoadmin.progress.bar.notification.template:
        class: %uneak.portoadmin.progress.bar.notification.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_progress_bar }

    uneak.portoadmin.message.notification.template:
        class: %uneak.portoadmin.message.notification.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_message }

    uneak.portoadmin.icon.message.notification.template:
        class: %uneak.portoadmin.icon.message.notification.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_icon_message }

    uneak.portoadmin.search.template:
        class: %uneak.portoadmin.search.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_search }

    uneak.portoadmin.brand.template:
        class: %uneak.portoadmin.brand.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_brand }