parameters:
    uneak.portoadmin.menu.template.class: Uneak\PortoAdminBundle\Templates\Menu\MenuTemplate
    uneak.portoadmin.user.template.class: Uneak\PortoAdminBundle\Templates\User\UserTemplate
    uneak.portoadmin.breadcrumb.template.class: Uneak\PortoAdminBundle\Templates\Breadcrumb\BreadcrumbTemplate

services:
    uneak.portoadmin.menu.template:
        class: %uneak.portoadmin.menu.template.class%
        tags:
            - { name: uneak.blocksmanager.template, model: block_menu }

    uneak.portoadmin.user.template:
        class: %uneak.portoadmin.user.template.class%
        tags:
            - { name: uneak.blocksmanager.template, model: block_user }


    uneak.portoadmin.breadcrumb.template:
        class: %uneak.portoadmin.breadcrumb.template.class%
        tags:
            - { name: uneak.blocksmanager.template, model: block_breadcrumb }