parameters:
    uneak.portoadmin.menu.template.class: Uneak\PortoAdminBundle\Templates\Menu\MenuTemplate
    uneak.portoadmin.mainmenu.template.class: Uneak\PortoAdminBundle\Templates\Menu\MainMenuTemplate
    uneak.portoadmin.usermenu.template.class: Uneak\PortoAdminBundle\Templates\Menu\UserMenuTemplate
    uneak.portoadmin.entity.content.headermenu.template.class: Uneak\PortoAdminBundle\Templates\Menu\EntityContentHeaderMenuTemplate
    uneak.portoadmin.entitymenu.template.class: Uneak\PortoAdminBundle\Templates\Menu\EntityMenuTemplate
    uneak.portoadmin.entity.toolbarmenu.template.class: Uneak\PortoAdminBundle\Templates\Menu\EntityToolbarMenuTemplate

    uneak.portoadmin.grid.actions.template.class: Uneak\PortoAdminBundle\Templates\Menu\GridActionsMenuTemplate

    uneak.portoadmin.datatable.template.class: Uneak\PortoAdminBundle\Templates\Datatable\DatatableTemplate

    uneak.portoadmin.photo.template.class: Uneak\PortoAdminBundle\Templates\Photo\PhotoTemplate

    uneak.portoadmin.user.template.class: Uneak\PortoAdminBundle\Templates\User\UserTemplate
    uneak.portoadmin.breadcrumb.template.class: Uneak\PortoAdminBundle\Templates\Breadcrumb\BreadcrumbTemplate

    uneak.portoadmin.notifications.template.class: Uneak\PortoAdminBundle\Templates\Notification\NotificationsTemplate
    uneak.portoadmin.notification.template.class: Uneak\PortoAdminBundle\Templates\Notification\NotificationTemplate

    uneak.portoadmin.progress.bar.notification.template.class: Uneak\PortoAdminBundle\Templates\Notification\ProgressBarTemplate
    uneak.portoadmin.message.notification.template.class: Uneak\PortoAdminBundle\Templates\Notification\MessageTemplate
    uneak.portoadmin.icon.message.notification.template.class: Uneak\PortoAdminBundle\Templates\Notification\IconMessageTemplate

    uneak.portoadmin.search.template.class: Uneak\PortoAdminBundle\Templates\Search\SearchTemplate

    uneak.portoadmin.brand.main.ui.template.class: Uneak\PortoAdminBundle\Templates\Brand\BrandMainUITemplate
    uneak.portoadmin.brand.form.ui.template.class: Uneak\PortoAdminBundle\Templates\Brand\BrandFormUITemplate

    uneak.portoadmin.widget.wrapper.template.class: Uneak\PortoAdminBundle\Templates\Widget\WidgetWrapperTemplate
    uneak.portoadmin.widget.tasks.template.class: Uneak\PortoAdminBundle\Templates\Widget\WidgetTasksTemplate

    uneak.portoadmin.widget.stats.progress.template.class: Uneak\PortoAdminBundle\Templates\Widget\WidgetStatsProgressTemplate
    uneak.portoadmin.widget.stats.template.class: Uneak\PortoAdminBundle\Templates\Widget\WidgetStatsTemplate

    uneak.portoadmin.widget.status.template.class: Uneak\PortoAdminBundle\Templates\Widget\WidgetStatusTemplate

    uneak.portoadmin.panel.template.class: Uneak\PortoAdminBundle\Templates\Panel\PanelTemplate
    uneak.portoadmin.carousel.template.class: Uneak\PortoAdminBundle\Templates\Carousel\CarouselTemplate
    uneak.portoadmin.content.template.class: Uneak\PortoAdminBundle\Templates\Content\ContentTemplate
    uneak.portoadmin.tabs.template.class: Uneak\PortoAdminBundle\Templates\UIElements\TabsTemplate
    uneak.portoadmin.accordion.template.class: Uneak\PortoAdminBundle\Templates\Accordion\AccordionTemplate
    uneak.portoadmin.counter.template.class: Uneak\PortoAdminBundle\Templates\Counter\CounterTemplate
    uneak.portoadmin.teaser.template.class: Uneak\PortoAdminBundle\Templates\Teaser\TeaserTemplate
    uneak.portoadmin.user.badge.template.class: Uneak\PortoAdminBundle\Templates\User\UserBadgeTemplate


    uneak.portoadmin.layout.main.interface.template.class: Uneak\PortoAdminBundle\Templates\Layout\MainInterfaceTemplate
    uneak.portoadmin.layout.content.template.class: Uneak\PortoAdminBundle\Templates\Layout\ContentTemplate
    uneak.portoadmin.layout.header.template.class: Uneak\PortoAdminBundle\Templates\Layout\HeaderTemplate
    uneak.portoadmin.layout.left.sidebar.template.class: Uneak\PortoAdminBundle\Templates\Layout\LeftSidebarTemplate
    uneak.portoadmin.layout.right.sidebar.template.class: Uneak\PortoAdminBundle\Templates\Layout\RightSidebarTemplate
    uneak.portoadmin.layout.page.body.template.class: Uneak\PortoAdminBundle\Templates\Layout\PageBodyTemplate
    uneak.portoadmin.layout.page.header.template.class: Uneak\PortoAdminBundle\Templates\Layout\PageHeaderTemplate

    uneak.portoadmin.layout.entity.template.class: Uneak\PortoAdminBundle\Templates\Layout\EntityTemplate
    uneak.portoadmin.layout.entity.sidebar.template.class: Uneak\PortoAdminBundle\Templates\Layout\EntitySidebarTemplate
    uneak.portoadmin.layout.entity.content.template.class: Uneak\PortoAdminBundle\Templates\Layout\EntityContentTemplate
    uneak.portoadmin.layout.entity.content.scroll.template.class: Uneak\PortoAdminBundle\Templates\Layout\EntityContentScrollTemplate

    uneak.portoadmin.layout.form.interface.template.class: Uneak\PortoAdminBundle\Templates\Layout\FormInterfaceTemplate

    uneak.portoadmin.form.template.class: Uneak\PortoAdminBundle\Templates\Form\FormTemplate

    uneak.portoadmin.twig.template.class: Uneak\PortoAdminBundle\Templates\Content\TwigTemplate

    uneak.portoadmin.pnotify.template.class: Uneak\PortoAdminBundle\Templates\PNotify\PNotifyTemplate

    uneak.portoadmin.todos.template.class: Uneak\PortoAdminBundle\Templates\Todo\TodosTemplate
    uneak.portoadmin.todo.template.class: Uneak\PortoAdminBundle\Templates\Todo\TodoTemplate

services:

    uneak.portoadmin.todos.template.template:
        class: %uneak.portoadmin.todos.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_todos }

    uneak.portoadmin.todo.template.template:
        class: %uneak.portoadmin.todo.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_todo }

    uneak.portoadmin.pnotify.template:
        class: %uneak.portoadmin.pnotify.template.class%
        arguments:
            - @session
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_pnotify }

    uneak.portoadmin.twig.template:
        class: %uneak.portoadmin.twig.template.class%
        arguments:
            - @service_container
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_twig }

    uneak.portoadmin.form.template:
        class: %uneak.portoadmin.form.template.class%
        arguments:
            - @uneak.formsmanager
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_form }

    uneak.portoadmin.datatable.template:
        class: %uneak.portoadmin.datatable.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_datatable }

    uneak.portoadmin.menu.template:
        class: %uneak.portoadmin.menu.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_menu }

    uneak.portoadmin.grid.actions.template:
        class: %uneak.portoadmin.grid.actions.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_grid_actions_menu }

    uneak.portoadmin.entitymenu.template:
        class: %uneak.portoadmin.entitymenu.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_entity_menu }

    uneak.portoadmin.entity.toolbarmenu.template:
        class: %uneak.portoadmin.entity.toolbarmenu.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_entity_toolbar_menu }

    uneak.portoadmin.carousel.template:
        class: %uneak.portoadmin.carousel.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_carousel }

    uneak.portoadmin.user.badge.template:
        class: %uneak.portoadmin.user.badge.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_user_badge }

    uneak.portoadmin.teaser.template:
        class: %uneak.portoadmin.teaser.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_teaser }

    uneak.portoadmin.photo.template:
        class: %uneak.portoadmin.photo.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_photo }

    uneak.portoadmin.counter.template:
        class: %uneak.portoadmin.counter.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_counter }

    uneak.portoadmin.accordion.template:
        class: %uneak.portoadmin.accordion.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_accordion }

    uneak.portoadmin.tabs.template:
        class: %uneak.portoadmin.tabs.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_tabs }

    uneak.portoadmin.content.template:
        class: %uneak.portoadmin.content.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_content }

    uneak.portoadmin.panel.template:
        class: %uneak.portoadmin.panel.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_panel }

    uneak.portoadmin.mainmenu.template:
        class: %uneak.portoadmin.mainmenu.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_main_menu }

    uneak.portoadmin.entity.content.headermenu.template:
        class: %uneak.portoadmin.entity.content.headermenu.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_entity_content_header_menu }

    uneak.portoadmin.usermenu.template:
        class: %uneak.portoadmin.usermenu.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_user_menu }



    uneak.portoadmin.user.template:
        class: %uneak.portoadmin.user.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_user }

    uneak.portoadmin.breadcrumb.template:
        class: %uneak.portoadmin.breadcrumb.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_breadcrumb }

    uneak.portoadmin.notifications.template:
        class: %uneak.portoadmin.notifications.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_notifications }

    uneak.portoadmin.notification.template:
        class: %uneak.portoadmin.notification.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_notification }

    uneak.portoadmin.progress.bar.notification.template:
        class: %uneak.portoadmin.progress.bar.notification.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_progress_bar }

    uneak.portoadmin.message.notification.template:
        class: %uneak.portoadmin.message.notification.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_message }

    uneak.portoadmin.icon.message.notification.template:
        class: %uneak.portoadmin.icon.message.notification.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_icon_message }

    uneak.portoadmin.search.template:
        class: %uneak.portoadmin.search.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_search }

    uneak.portoadmin.brand.main.ui.template:
        class: %uneak.portoadmin.brand.main.ui.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_brand_main_ui }

    uneak.portoadmin.brand.form.ui.template:
        class: %uneak.portoadmin.brand.form.ui.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_brand_form_ui }


    uneak.portoadmin.widget.wrapper.template:
        class: %uneak.portoadmin.widget.wrapper.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_widget_wrapper }

    uneak.portoadmin.widget.tasks.template:
        class: %uneak.portoadmin.widget.tasks.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_widget_tasks }

    uneak.portoadmin.widget.stats.template:
        class: %uneak.portoadmin.widget.stats.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_widget_stats }

    uneak.portoadmin.widget.status.template:
        class: %uneak.portoadmin.widget.status.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_widget_status }

    uneak.portoadmin.widget.stats.progress.template:
        class: %uneak.portoadmin.widget.stats.progress.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_template_widget_stats_progress }

    uneak.portoadmin.layout.main.interface.template:
        class: %uneak.portoadmin.layout.main.interface.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_main_interface }

    uneak.portoadmin.layout.content.template:
        class: %uneak.portoadmin.layout.content.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_content }

    uneak.portoadmin.layout.header.template:
        class: %uneak.portoadmin.layout.header.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_header }

    uneak.portoadmin.layout.left.sidebar.template:
        class: %uneak.portoadmin.layout.left.sidebar.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_left_sidebar }

    uneak.portoadmin.layout.right.sidebar.template:
        class: %uneak.portoadmin.layout.right.sidebar.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_right_sidebar }

    uneak.portoadmin.layout.page.body.template:
        class: %uneak.portoadmin.layout.page.body.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_page_body }

    uneak.portoadmin.layout.page.header.template:
        class: %uneak.portoadmin.layout.page.header.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_page_header }

    uneak.portoadmin.layout.entity.template:
        class: %uneak.portoadmin.layout.entity.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_entity }

    uneak.portoadmin.layout.entity.sidebar.template:
        class: %uneak.portoadmin.layout.entity.sidebar.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_entity_sidebar }

    uneak.portoadmin.layout.entity.content.template:
        class: %uneak.portoadmin.layout.entity.content.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_entity_content }

    uneak.portoadmin.layout.entity.content.scroll.template:
        class: %uneak.portoadmin.layout.entity.content.scroll.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_entity_content_scroll }

    uneak.portoadmin.layout.form.interface.template:
        class: %uneak.portoadmin.layout.form.interface.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: layout_template_form_interface }