


porto_admin_user_avatar:
    quality: 100
    filters:
        upscale: { min: [35, 35] }
        thumbnail: { size: [35, 35], mode: outbound }

porto_admin_brand_photo:
    quality: 100
    filters:
        relative_resize: { heighten: 35 }