


porto_admin_user_avatar_35:
    quality: 100
    filters:
        upscale: { min: [35, 35] }
        thumbnail: { size: [35, 35], mode: outbound }

porto_admin_brand_photo:
    quality: 100
    filters:
        relative_resize: { heighten: 35 }


porto_admin_user_badge_cover:
    quality: 100
    filters:
        upscale: { min: [798, 115] }
        thumbnail: { size: [798, 115], mode: outbound }

porto_admin_user_avatar_100:
    quality: 100
    filters:
        upscale: { min: [100, 100] }
        thumbnail: { size: [100, 100], mode: outbound }

porto_admin_entity_photo:
    quality: 100
    filters:
        upscale: { min: [229, 229] }
        thumbnail: { size: [229, 229], mode: outbound }