
parameters:
    knp_menu.voter.uri.class: Uneak\PortoAdminBundle\Menu\Matcher\Voter\UriVoter
    uneak.portoadmin.layout.controller.listener.class: Uneak\PortoAdminBundle\EventListener\LayoutControllerListener

    uneak.crud.handler.class: Uneak\PortoAdminBundle\Handler\CrudHandler

    uneak.admin.page.layout.class: Uneak\PortoAdminBundle\LayoutBuilder\AdminPageLayoutBuilder
    uneak.admin.form.layout.class: Uneak\PortoAdminBundle\LayoutBuilder\AdminFormLayoutBuilder
    uneak.admin.page.entity.layout.class: Uneak\PortoAdminBundle\LayoutBuilder\AdminPageEntityLayoutBuilder
    uneak.admin.page.profile.layout.class: Uneak\PortoAdminBundle\LayoutBuilder\AdminPageProfileLayoutBuilder

    uneak.admin.crud.handler.class: Uneak\PortoAdminBundle\Handler\CrudHandler


services:

    uneak.admin.crud.handler:
        class: %uneak.admin.crud.handler.class%
        arguments:
            - @form.factory
            - @uneak.blocksmanager.builder
            - @uneak.routesmanager.grid.helper
            - @uneak.routesmanager.menu.helper

    uneak.admin.form.layout:
        class: %uneak.admin.form.layout.class%

    uneak.admin.page.layout:
        class: %uneak.admin.page.layout.class%

    uneak.admin.page.entity.layout:
        class: %uneak.admin.page.entity.layout.class%
        arguments:
            - @uneak.blocksmanager.blocks
            - @uneak.routesmanager.menu.helper
            - @form.factory
            - @vich_uploader.templating.helper.uploader_helper

    uneak.admin.page.profile.layout:
        class: %uneak.admin.page.profile.layout.class%
        arguments:
            - @uneak.blocksmanager.blocks
            - @vich_uploader.templating.helper.uploader_helper


    uneak.crud.handler:
        class: %uneak.crud.handler.class%
        arguments:
            - @uneak.blocksmanager.builder
            - @uneak.blocksmanager.blocks
            - @uneak.routesmanager.menu.helper
            - @form.factory
            - @vich_uploader.templating.helper.uploader_helper

    knp_menu.voter.uri:
        class: %knp_menu.voter.uri.class%
        tags:
            - { name: knp_menu.voter, request: true }


    uneak.portoadmin.layout.controller.listener:
        class: %uneak.portoadmin.layout.controller.listener.class%
        arguments:
            - @router
            - @uneak.blocksmanager.builder
            - @uneak.blocksmanager.blocks
            - @vich_uploader.templating.helper.uploader_helper

        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }


