
parameters:
    knp_menu.voter.uri.class: Uneak\PortoAdminBundle\Menu\Matcher\Voter\UriVoter

services:
    knp_menu.voter.uri:
        class: %knp_menu.voter.uri.class%
        tags:
            - { name: knp_menu.voter, request: true }