
parameters:
    knp_menu.voter.uri.class: Uneak\PortoAdminBundle\Menu\Matcher\Voter\UriVoter
    uneak.portoadmin.layout.controller.listener.class: Uneak\PortoAdminBundle\EventListener\LayoutControllerListener


services:
    knp_menu.voter.uri:
        class: %knp_menu.voter.uri.class%
        tags:
            - { name: knp_menu.voter, request: true }


    uneak.portoadmin.layout.controller.listener:
        class: %uneak.portoadmin.layout.controller.listener.class%
        arguments:
            - @router
            - @uneak.blocksmanager.builder
            - @uneak.blocksmanager.blocks
            - @vich_uploader.templating.helper.uploader_helper

        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }


