block_menu_template: "UneakPortoAdminBundle:Block:menu.html.twig"
block_main_menu_template: "UneakPortoAdminBundle:Block:main_menu.html.twig"
block_user_template: "UneakPortoAdminBundle:Block:user.html.twig"


block_breadcrumb_template: "UneakPortoAdminBundle:Block:menu.html.twig"
block_entity_toolbar_menu_template: "UneakPortoAdminBundle:Block:menu.html.twig"
block_entity_menu_template: "UneakPortoAdminBundle:Block:menu.html.twig"
block_entity_content_header_menu_template: "UneakPortoAdminBundle:Block:menu.html.twig"
block_grid_actions_menu_template: "UneakPortoAdminBundle:Block:menu.html.twig"


knp_user_menu_template: "UneakPortoAdminBundle:KnpMenu:user_menu_template.html.twig"
knp_main_menu_template: "UneakPortoAdminBundle:KnpMenu:main_menu_template.html.twig"
knp_entity_content_header_menu_template: "UneakPortoAdminBundle:KnpMenu:entity_content_header_menu_template.html.twig"
knp_breadcrumb_menu_template: "UneakPortoAdminBundle:KnpMenu:breadcrumb_template.html.twig"
knp_entity_menu_template: "UneakPortoAdminBundle:KnpMenu:entity_template.html.twig"
knp_entity_toolbar_menu_template: "UneakPortoAdminBundle:KnpMenu:entity_toolbar_template.html.twig"
knp_grid_actions_menu_template: "UneakPortoAdminBundle:KnpMenu:grid_actions_template.html.twig"

block_notification_template: "UneakPortoAdminBundle:Block:notification.html.twig"
block_notifications_template: "UneakPortoAdminBundle:Block:notifications.html.twig"

block_form_template: "UneakPortoAdminBundle:Block:Form/form.html.twig"

block_photo_template: "UneakPortoAdminBundle:Block:photo.html.twig"


block_progress_bar_notification_template: "UneakPortoAdminBundle:Block:progress_bar_notification.html.twig"
block_message_notification_template: "UneakPortoAdminBundle:Block:message_notification.html.twig"
block_icon_message_notification_template: "UneakPortoAdminBundle:Block:icon_message_notification.html.twig"

block_search_template: "UneakPortoAdminBundle:Block:search.html.twig"
block_brand_main_ui_template: "UneakPortoAdminBundle:Block:brand_main_ui.html.twig"
block_brand_form_ui_template: "UneakPortoAdminBundle:Block:brand_form_ui.html.twig"

block_widget_wrapper_template: "UneakPortoAdminBundle:Block:widget_wrapper.html.twig"
block_widget_tasks_template: "UneakPortoAdminBundle:Block:widget_tasks.html.twig"

block_widget_status_template: "UneakPortoAdminBundle:Block:widget_status.html.twig"

block_widget_stats_template: "UneakPortoAdminBundle:Block:widget_stats.html.twig"
block_widget_stats_progress_template: "UneakPortoAdminBundle:Block:widget_stats_progress.html.twig"

block_panel_template: "UneakPortoAdminBundle:Block:panel.html.twig"
block_carousel_template: "UneakPortoAdminBundle:Block:carousel.html.twig"
block_tabs_template: "UneakPortoAdminBundle:Block:tabs.html.twig"
block_accordion_template: "UneakPortoAdminBundle:Block:accordion.html.twig"
block_counter_template: "UneakPortoAdminBundle:Block:counter.html.twig"
block_teaser_template: "UneakPortoAdminBundle:Block:teaser.html.twig"
block_user_badge_template: "UneakPortoAdminBundle:Block:user_badge.html.twig"
block_datatable_template: "UneakPortoAdminBundle:Block:datatable.html.twig"


# FORM
form_gender_theme_template: "UneakPortoAdminBundle:Form:gender_theme.html.twig"
form_collection_theme_template: "UneakPortoAdminBundle:Form:collection_theme.html.twig"
form_select2_theme_template: "UneakPortoAdminBundle:Form:select2_theme.html.twig"



# LAYOUT
layout_main_interface_template: "UneakPortoAdminBundle:Layout:layout_main_interface.html.twig"
layout_content_template: "UneakPortoAdminBundle:Layout:layout_content.html.twig"
layout_header_template: "UneakPortoAdminBundle:Layout:layout_header.html.twig"
layout_left_sidebar_template: "UneakPortoAdminBundle:Layout:layout_left_sidebar.html.twig"
layout_right_sidebar_template: "UneakPortoAdminBundle:Layout:layout_right_sidebar.html.twig"
layout_page_body_template: "UneakPortoAdminBundle:Layout:layout_page_body.html.twig"
layout_page_header_template: "UneakPortoAdminBundle:Layout:layout_page_header.html.twig"
layout_entity_template: "UneakPortoAdminBundle:Layout:layout_entity.html.twig"
layout_entity_sidebar_template: "UneakPortoAdminBundle:Layout:layout_entity_sidebar.html.twig"
layout_entity_content_template: "UneakPortoAdminBundle:Layout:layout_entity_content.html.twig"
layout_entity_content_scroll_template: "UneakPortoAdminBundle:Layout:layout_entity_content_scroll.html.twig"

layout_form_interface_template: "UneakPortoAdminBundle:Layout:layout_form_interface.html.twig"


# SCRIPT
porto_admin_scrollable_script_template: "UneakPortoAdminBundle:Script:script_scrollable.html.twig"
porto_admin_sidebar_widget_wrapper_script_template: "UneakPortoAdminBundle:Script:script_widget_wrapper.html.twig"
porto_admin_sidebar_toggle_script_template: "UneakPortoAdminBundle:Script:script_sidebar_toggle.html.twig"
porto_admin_datatable_script_template: "UneakPortoAdminBundle:Script:script_datatable.html.twig"
form_collection_script_template: "UneakPortoAdminBundle:Script:script_uneak_collection.html.twig"
pnotify_script_template: "UneakPortoAdminBundle:Script:script_pnotify.html.twig"
select2_script_template: "UneakPortoAdminBundle:Script:script_select2.html.twig"


# FOS USER
user_security_login: UneakPortoAdminBundle:FOSUser:Security/login.html.twig
user_resetting_request: UneakPortoAdminBundle:FOSUser:Resetting/request.html.twig
user_resetting_reset: UneakPortoAdminBundle:FOSUser:Resetting/reset.html.twig
user_resetting_password_already_requested: UneakPortoAdminBundle:FOSUser:Resetting/passwordAlreadyRequested.html.twig
user_resetting_check_email: UneakPortoAdminBundle:FOSUser:Resetting/checkEmail.html.twig
user_resetting_change_password_change_password: UneakPortoAdminBundle:FOSUser:ChangePassword/changePassword.html.twig
user_profile_show: UneakPortoAdminBundle:FOSUser:Profile/show.html.twig
user_profile_edit: UneakPortoAdminBundle:FOSUser:Profile/edit.html.twig
user_registration_register: UneakPortoAdminBundle:FOSUser:Registration/register.html.twig

user_registration_email_confirmed: UneakPortoAdminBundle:FOSUser:Registration/emailConfirmed.html.twig


user_connect_login: UneakPortoAdminBundle:FOSUser:Connect/login.html.twig
user_connect_registration_success: UneakPortoAdminBundle:FOSUser:Connect/registration_success.html.twig
user_connect_registration: UneakPortoAdminBundle:FOSUser:Connect/registration.html.twig
user_connect_connect_success: UneakPortoAdminBundle:FOSUser:Connect/connect_success.html.twig
user_connect_connect_confirm: UneakPortoAdminBundle:FOSUser:Connect/connect_confirm.html.twig


