block_menu_template: "UneakPortoAdminBundle:Block:menu.html.twig"
block_main_menu_template: "UneakPortoAdminBundle:Block:main_menu.html.twig"
block_user_template: "UneakPortoAdminBundle:Block:user.html.twig"
block_breadcrumb_template: "UneakPortoAdminBundle:Block:breadcrumb.html.twig"

knp_user_menu_template: "UneakPortoAdminBundle:KnpMenu:user_menu_template.html.twig"
knp_main_menu_template: "UneakPortoAdminBundle:KnpMenu:main_menu_template.html.twig"
knp_breadcrumb_menu_template: "UneakPortoAdminBundle:KnpMenu:breadcrumb_template.html.twig"

block_notification_template: "UneakPortoAdminBundle:Block:notification.html.twig"
block_notifications_template: "UneakPortoAdminBundle:Block:notifications.html.twig"


block_progress_bar_notification_template: "UneakPortoAdminBundle:Block:progress_bar_notification.html.twig"
block_message_notification_template: "UneakPortoAdminBundle:Block:message_notification.html.twig"
block_icon_message_notification_template: "UneakPortoAdminBundle:Block:icon_message_notification.html.twig"

block_search_template: "UneakPortoAdminBundle:Block:search.html.twig"
block_brand_template: "UneakPortoAdminBundle:Block:brand.html.twig"

block_widget_wrapper_template: "UneakPortoAdminBundle:Block:widget_wrapper.html.twig"
block_widget_tasks_template: "UneakPortoAdminBundle:Block:widget_tasks.html.twig"

block_widget_stats_template: "UneakPortoAdminBundle:Block:widget_stats.html.twig"
block_widget_stats_progress_template: "UneakPortoAdminBundle:Block:widget_stats_progress.html.twig"

block_panel_template: "UneakPortoAdminBundle:Block:panel.html.twig"
block_carousel_template: "UneakPortoAdminBundle:Block:carousel.html.twig"
block_tabs_template: "UneakPortoAdminBundle:Block:tabs.html.twig"
block_accordion_template: "UneakPortoAdminBundle:Block:accordion.html.twig"
block_counter_template: "UneakPortoAdminBundle:Block:counter.html.twig"
block_teaser_template: "UneakPortoAdminBundle:Block:teaser.html.twig"
block_user_badge_template: "UneakPortoAdminBundle:Block:user_badge.html.twig"


# LAYOUT
layout_main_interface_template: "UneakPortoAdminBundle:Layout:layout_main_interface.html.twig"
layout_content_template: "UneakPortoAdminBundle:Layout:layout_content.html.twig"
layout_header_template: "UneakPortoAdminBundle:Layout:layout_header.html.twig"
layout_left_sidebar_template: "UneakPortoAdminBundle:Layout:layout_left_sidebar.html.twig"
layout_right_sidebar_template: "UneakPortoAdminBundle:Layout:layout_right_sidebar.html.twig"
layout_page_body_template: "UneakPortoAdminBundle:Layout:layout_page_body.html.twig"
layout_page_header_template: "UneakPortoAdminBundle:Layout:layout_page_header.html.twig"

