<?php

	namespace Uneak\FieldBundle\Entity;

    use Uneak\PortoAdminBundle\Entity\APIRepository;

    /**
	 * ParticipantRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class FieldRepository extends APIRepository {

    }
