<?php

	namespace Uneak\FieldBundle\Entity;

    use Uneak\PortoAdminBundle\Entity\APIRepository;

    /**
	 * ParticipantRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class FieldRepository extends APIRepository {

        public function findFields($group)
        {
            $qb = $this->_em->createQueryBuilder();
            $qb
                ->select('field')
                ->from('UneakFieldBundle:Field', 'field')
                ->innerJoin('field.group', 'fieldgroup')
                ->where(
                    $qb->expr()->eq('fieldgroup.slug', ':fieldgroup')
                )
                ->setParameter("fieldgroup", $group)
                ->orderBy("field.sort", "DESC");

            return $qb->getQuery()->getResult();
        }


	}
