parameters:
    uneak.admin.user.admin.class: UserBundle\Admin\User

services:

    uneak.admin.user.admin:
        class: %uneak.admin.user.admin.class%
        arguments: [ users ]
        calls:
            - [ setController, [ UserBundle\Controller\UserAdminController ] ]
        tags:
            -  { name: uneak.routesmanager.route }

