user_security_login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }
    requirements:
        _method: GET|POST


user_security_check:
    path: /login_check
    defaults: { _controller: UserBundle:Security:check }
    requirements:
        _method: POST


user_security_logout:
    path: /logout
    defaults: { _controller: UserBundle:Security:logout }
    requirements:
        _method: GET


user_profile_show:
    path: /profile
    defaults: { _controller: UserBundle:Profile:show }
    requirements:
        _method: GET

user_profile_connect:
    path: /profile/social
    defaults: { _controller: UserBundle:Profile:connect }
    requirements:
        _method: GET

user_profile_disconnect:
    path: /profile/social/disconnect/{service}
    defaults: { _controller: UserBundle:Profile:disconnectService }
    requirements:
        _method: GET

user_profile_edit:
    path: /profile/edit
    defaults: { _controller: UserBundle:Profile:edit }
    requirements:
        _method: GET|POST


user_registration_register:
    path: /register/{key}
    defaults: { _controller: UserBundle:Registration:register, key: null }
    requirements:
        _method: GET|POST



user_registration_check_email:
    path: /register/check-email/{username}
    defaults: { _controller: UserBundle:Registration:checkEmail }
    requirements:
        _method: GET

user_registration_email_confirmed:
    path: /register/email-confirmed/{username}
    defaults: { _controller: UserBundle:Registration:emailConfirmed }
    requirements:
        _method: GET

user_registration_confirm:
    path: /register/email-confirm/{token}
    defaults: { _controller: UserBundle:Registration:emailConfirm }
    requirements:
        _method: GET


user_registration_confirmed:
    path: /register/confirmed/{username}
    defaults: { _controller: UserBundle:Registration:confirmed }
    requirements:
        _method: GET


user_resetting_request:
    path: /resetting/request
    defaults: { _controller: UserBundle:Resetting:request }
    requirements:
        _method: GET


user_resetting_send_email:
    path: /resetting/send-email
    defaults: { _controller: UserBundle:Resetting:sendEmail }
    requirements:
        _method: POST


user_resetting_check_email:
    path: /resetting/check-email
    defaults: { _controller: UserBundle:Resetting:checkEmail }
    requirements:
        _method: GET


user_resetting_reset:
    path: /resetting/reset/{token}
    defaults: { _controller: UserBundle:Resetting:reset }
    requirements:
        _method: GET|POST


user_change_password:
    path: /profile/change-password
    defaults: { _controller: UserBundle:ChangePassword:changePassword }
    requirements:
        _method: GET|POST

