user_security_login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }
    requirements:
        _method: GET|POST


user_security_check:
    path: /login_check
    defaults: { _controller: UserBundle:Security:check }
    requirements:
        _method: POST


user_security_logout:
    path: /logout
    defaults: { _controller: UserBundle:Security:logout }
    requirements:
        _method: GET


user_profile_show:
    path: /profile
    defaults: { _controller: UserBundle:Profile:show }
    requirements:
        _method: GET

user_profile_connect:
    path: /profile/social
    defaults: { _controller: UserBundle:Profile:connect }
    requirements:
        _method: GET



user_profile_edit:
    path: /profile/edit
    defaults: { _controller: UserBundle:Profile:edit }
    requirements:
        _method: GET|POST


user_registration_register:
    path: /register/{key}
    defaults: { _controller: UserBundle:Registration:register, key: null }
    requirements:
        _method: GET|POST



user_registration_check_email:
    path: /register/check-email/{username}
    defaults: { _controller: UserBundle:Registration:checkEmail }
    requirements:
        _method: GET

user_registration_email_confirmed:
    path: /register/email-confirmed/{username}
    defaults: { _controller: UserBundle:Registration:emailConfirmed }
    requirements:
        _method: GET

user_registration_confirm:
    path: /register/email-confirm/{token}
    defaults: { _controller: UserBundle:Registration:emailConfirm }
    requirements:
        _method: GET


user_registration_confirmed:
    path: /register/confirmed/{username}
    defaults: { _controller: UserBundle:Registration:confirmed }
    requirements:
        _method: GET


user_resetting_request:
    path: /resetting/request
    defaults: { _controller: UserBundle:Resetting:request }
    requirements:
        _method: GET


user_resetting_send_email:
    path: /resetting/send-email
    defaults: { _controller: UserBundle:Resetting:sendEmail }
    requirements:
        _method: POST


user_resetting_check_email:
    path: /resetting/check-email
    defaults: { _controller: UserBundle:Resetting:checkEmail }
    requirements:
        _method: GET


user_resetting_reset:
    path: /resetting/reset/{token}
    defaults: { _controller: UserBundle:Resetting:reset }
    requirements:
        _method: GET|POST


user_change_password:
    path: /profile/change-password
    defaults: { _controller: UserBundle:ChangePassword:changePassword }
    requirements:
        _method: GET|POST



user_oauth_connect:
    path: /connect
    defaults: { _controller: UserBundle:Connect:connect }


user_oauth_disconnect_service:
    path: /disconnect/service/{service}
    defaults: { _controller: UserBundle:Connect:disconnectService }


user_oauth_register_service:
    path: /register/service/{service}
    defaults: { _controller: UserBundle:Connect:registerService }


user_oauth_connect_service:
    path: /connect/service/{service}
    defaults: { _controller: UserBundle:Connect:connectService }


#user_oauth_connect_registration:
#    path: /connect/registration/{key}
#    defaults: { _controller: UserBundle:Connect:registration }


user_oauth_service_redirect:
    path: /connect/{service}
    defaults: { _controller: UserBundle:Connect:redirectToService }


user_facebook_login:
    path: /connect/check-facebook


user_google_login:
    pattern: /connect/check-google


user_twitter_login:
    pattern: /connect/check-twitter