member_security_login:
    path: /login
    defaults: { _controller: MemberBundle:Security:login }
    requirements:
        _method: GET|POST


member_security_check:
    path: /login_check
    defaults: { _controller: MemberBundle:Security:check }
    requirements:
        _method: POST


member_security_logout:
    path: /logout
    defaults: { _controller: MemberBundle:Security:logout }
    requirements:
        _method: GET


member_profile_show:
    path: /profile
    defaults: { _controller: MemberBundle:Profile:show }
    requirements:
        _method: GET


member_profile_edit:
    path: /profile/edit
    defaults: { _controller: MemberBundle:Profile:edit }
    requirements:
        _method: GET|POST


member_registration_register:
    path: /register
    defaults: { _controller: MemberBundle:Registration:register }
    requirements:
        _method: GET|POST


member_registration_check_email:
    path: /register/check-email
    defaults: { _controller: MemberBundle:Registration:checkEmail }
    requirements:
        _method: GET


member_registration_confirm:
    path: /register/confirm/{token}
    defaults: { _controller: MemberBundle:Registration:confirm }
    requirements:
        _method: GET


member_registration_confirmed:
    path: /register/confirmed
    defaults: { _controller: MemberBundle:Registration:confirmed }
    requirements:
        _method: GET


member_resetting_request:
    path: /resetting/request
    defaults: { _controller: MemberBundle:Resetting:request }
    requirements:
        _method: GET


member_resetting_send_email:
    path: /resetting/send-email
    defaults: { _controller: MemberBundle:Resetting:sendEmail }
    requirements:
        _method: POST


member_resetting_check_email:
    path: /resetting/check-email
    defaults: { _controller: MemberBundle:Resetting:checkEmail }
    requirements:
        _method: GET


member_resetting_reset:
    path: /resetting/reset/{token}
    defaults: { _controller: MemberBundle:Resetting:reset }
    requirements:
        _method: GET|POST


member_change_password:
    path: /profile/change-password
    defaults: { _controller: MemberBundle:ChangePassword:changePassword }
    requirements:
        _method: GET|POST



member_oauth_connect:
    path: /connect
    defaults: { _controller: MemberBundle:Connect:connect }


member_oauth_connect_service:
    path: /connect/service/{service}
    defaults: { _controller: MemberBundle:Connect:connectService }


member_oauth_connect_registration:
    path: /connect/registration/{key}
    defaults: { _controller: MemberBundle:Connect:registration }


member_oauth_service_redirect:
    path: /connect/{service}
    defaults: { _controller: MemberBundle:Connect:redirectToService }


member_facebook_login:
    path: /connect/check-facebook


member_google_login:
    pattern: /connect/check-google


member_twitter_login:
    pattern: /connect/check-twitter