parameters:
    uneak.admin.group.admin.class: ProspectGroupBundle\Admin\ProspectGroup
    uneak.admin.group.api.handler.class: ProspectGroupBundle\Handler\ProspectGroupAPIHandler
    uneak.admin.group.crud.handler.class: ProspectGroupBundle\Handler\ProspectGroupCRUDHandler

services:

    uneak.admin.group.admin:
        class: %uneak.admin.group.admin.class%
        arguments: [ groups ]
        calls:
            - [ setController, [ ProspectGroupBundle\Controller\ProspectGroupAdminController ] ]
            - [ setHandler, [ @uneak.admin.group.crud.handler ] ]
            - [ setParentPath, [ "clients.subject" ] ]
        tags:
            -  { name: uneak.routesmanager.route }

    uneak.admin.group.api.handler:
        class: %uneak.admin.group.api.handler.class%
        arguments:
            - @form.factory
            - @doctrine.orm.entity_manager
        calls:
            - [ setEntityClass, [ Uneak\FieldGroupBundle\Entity\FieldGroup ] ]


    uneak.admin.group.crud.handler:
        class: %uneak.admin.group.crud.handler.class%
        arguments:
            - @uneak.admin.group.api.handler
