parameters:
    uneak.admin.field.admin.class: GroupFieldBundle\Admin\GroupField
    uneak.admin.field.api.handler.class: GroupFieldBundle\Handler\GroupFieldAPIHandler
    uneak.admin.field.crud.handler.class: GroupFieldBundle\Handler\GroupFieldCRUDHandler

services:

    uneak.admin.field.admin:
        class: %uneak.admin.field.admin.class%
        arguments: [ fields ]
        calls:
            - [ setController, [ GroupFieldBundle\Controller\GroupFieldAdminController ] ]
            - [ setHandler, [ @uneak.admin.field.crud.handler ] ]
            - [ setParentPath, [ "groups.subject" ] ]
        tags:
            -  { name: uneak.routesmanager.route }

    uneak.admin.field.api.handler:
        class: %uneak.admin.field.api.handler.class%
        arguments:
            - @form.factory
            - @doctrine.orm.entity_manager
            - "GroupFieldBundle\Entity\GroupField"

    uneak.admin.field.crud.handler:
        class: %uneak.admin.field.crud.handler.class%
        arguments:
            - @uneak.admin.field.api.handler
