<?php

	namespace OAuthServerBundle\Entity;

    use Uneak\PortoAdminBundle\Entity\APIRepository;

    /**
	 * ClientRepository
	 *
	 * This class was generated by the Doctrine ORM. Add your own custom
	 * repository methods below.
	 */
	class ClientRepository extends APIRepository {

	}
