parameters:
    uneak.card.template.class: Uneak\MaterialDesignBundle\Templates\CardBlockTemplate

services:
    uneak.card.template:
        class: %uneak.card.template.class%
        tags:
            - { name: uneak.blocksmanager.template, alias: block_card_model }